services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: JULIA
      MYSQL_DATABASE: machine
      MYSQL_PASSWORD: root1234
       
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - machine_mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8081:8000"  # Mapea el puerto 8080 del host al puerto 8000 del contenedor
    depends_on:
      - mysql
    networks:
      - my_network
    environment:
      - DB_HOST=mysql_container
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root1234
      - DB_NAME=machine
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]


networks:
  my_network:
    driver: bridge

volumes:
  machine_mysql_data:





















    
